### ISSUE TITLE
Setting token does not work

### ISSUE THREAD

**Issue by sebastianfuehr** [Zarathustra2/GoTasks#8]
Setting the github token does not work if called before `GoTasks -gitissues`, since `saveGitToken()` does not check if the table exists. 

See here: [https://github.com/Zarathustra2/GoTasks/blob/2d7b607002077f775ffa5c1340272c3e2de1299b/git.go#L107](https://github.com/Zarathustra2/GoTasks/blob/2d7b607002077f775ffa5c1340272c3e2de1299b/git.go#L107)

**Comment by Zarathustra2** [comment]
Done.
